void _puts_recursion(char *);
void _putchar(int);
void _print_rev_recursion(char *);
int _strlen_recursion(char *);
int factorial(int);
int _pow_recursion(int, int);
int _sqrt_recursion(int);
int sqrt_helper(int, int, int);
int is_divisible(int , int);
int is_prime_number(int);
int is_palindrome(char *);
int is_palindrome_helper(char *, int, int);
